# Site settings
title: OC Creative
tagline: "Business Owners and Art Directors of Orange County, here's a curated list of the raddest creative professionals in your area."
url: "http://occreative.co" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Contact
name: Adam Rasheed
website: http://creatix.io
email: "adamrasheed91@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
